### ISSUE TITLE
Response microservice API definition

### ISSUE THREAD

**Issue by jsmithchollacreative** [jsmithdenverdev/formchata#13]
`sam deploy` elicits the following warning 
```txt
Your template contains a resource with logical ID "ServerlessRestApi", which is a reserved logical ID in AWS SAM. It could result in unexpected behaviors and is not recommended.
```

This is due to using an implicit API in the response microservice.

Define an explicit api for the response microservice.

```yaml
ResponseApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: FormchataCognitoAuthorizer
        Authorizers:
          FormchataCognitoAuthorizer:
            UserPoolArn: !Ref FormchataUserPoolArn
```
