### ISSUE TITLE
Microservice API stage's

### ISSUE THREAD

**Issue by jsmithchollacreative** [jsmithdenverdev/formchata#14]
Currently all API's are only using a Prod stage (see below). Update the API's to have proper environmental stages.

```yaml
Resources:
  FormApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod # TODO: this should be an environmental stage
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: FormchataCognitoAuthorizer
        Authorizers:
          FormchataCognitoAuthorizer:
            UserPoolArn: !Ref FormchataUserPoolArn
```
